---

# for complete list of usable vars, please check https://github.com/mesaguy/ansible-prometheus
prometheus_server_cfg:
  global:
    scrape_interval: 10s
  scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']

prometheus_components:
  - prometheus
  - alertmanager
  - node_exporter

prometheus_extra_opts:
  - '--storage.tsdb.retention=40d'
